version: 2.1

jobs:
  build:
    machine: true
    resource_class: shubham405/local-runner
    steps:
      - checkout

      - run:
          name: Debug environment
          command: |
            echo "User:"
            whoami
            echo "PWD:"
            pwd
            echo "Java:"
            java -version
            echo "Maven:"
            mvn -version
            echo "Files:"
            ls -l

      - run:
          name: Fix mvnw permission
          command: chmod +x mvnw

      - run:
          name: Build app
          command: ./mvnw clean package -DskipTests

      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar

  deploy:
    machine: true
    resource_class: shubham405/local-runner
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy locally
          command: |
            echo "Deploying locally..."
            mkdir -p /home/circleci/app
            cp target/*.jar /home/circleci/app/app.jar

      - run:
          name: Deploy success
          command: echo "App built and deployed locally"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
